title: KATHAN PATEL
description: Data Integration Analyst (Engineering Focused)| Databricks Certified
[LinkedIn](https://www.linkedin.com/in/YOUR_LINKEDIN_ID)|[Email](mailto:Kathanpatel1899@gmail.com)|[Download Resume](LINK_TO_PDF)
theme: jekyll-theme-cayman
show_downloads: true
google_analytics:
